fail_fast: true
repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.12

  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        name: docformatter
        language: python
        types: [python]
        description: "Formats docstrings to follow PEP 257."
        entry: docformatter
        args:
          - --in-place
          - --wrap-summaries=80
          - --wrap-descriptions=80

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.4
    hooks:
      - id: ruff
        args: [--fix]
        language_version: python3.12

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [python]
        exclude: ^(tests|data|docs)/
        args:
          - --no-strict-optional
          - --ignore-missing-imports
          - --no-incremental
          - --disable-error-code=override

      - id: pytest
        name: run tests
        entry: pytest tests -vv
        language: system
        always_run: true
        pass_filenames: false
