# fly.toml app configuration file generated for whatsapp-fact-checking-bot on 2025-01-29T10:57:33+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'whatsapp-fact-checking-bot'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8085
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = false
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

