name: Deploy
on:
  push:
    branches:
      - main

jobs:
  pre-commit-and-test:
    name: "Pre-commit and Test Python 3.12"
    runs-on: ubuntu-latest
    if: always()
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-github-actions-annotate-failures

      - name: Install bc
        run: sudo apt-get install -y bc

      - name: Install Graphviz
        uses: tlylt/install-graphviz@v1

      - name: PyTest with code coverage
        continue-on-error: true
        run: |
          pytest --cov=. --cov-report=term-missing --cov-report=xml --cov-branch
          echo "Listing files in current directory:"
          ls -la
          echo "Content of coverage.xml if it exists:"
          cat coverage.xml || echo "No coverage.xml found"
