name: Deploy
on:
  push:
    branches:
      - main

jobs:
  pre-commit-and-test:
    name: "Pre-commit and Test Python 3.9"
    runs-on: ubuntu-latest
    if: always()
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-github-actions-annotate-failures
        
      - name: Install Graphviz
        uses: tlylt/install-graphviz@v1

      - name: PyTest with code coverage
        continue-on-error: true
        run: |
          pytest --cov=. --cov-report=term-missing --cov-report=xml --cov-branch

      - name: Get the Coverage
        shell: bash
        run: |
          regex='<coverage.+line-rate="([0-9]+\.[0-9]+)".+>'
          line=$(grep -oP "$regex" coverage.xml)
          [[ $line =~ $regex ]]
          coverage=$( bc <<< "${BASH_REMATCH[1]}*100" )
          if (( $(echo "$coverage > 90" | bc -l) )); then
            COLOR=green
          else
            COLOR=red
          fi
          echo "COVERAGE=${coverage%.*}%" >> $GITHUB_ENV
          echo "COLOR=$COLOR" >> $GITHUB_ENV
      
      - name: Create Coverage Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ${{ secrets.GIST_ID }}
          filename: badge.json
          label: coverage
          message: ${{ env.COVERAGE }}
          color: ${{ env.COLOR }}

      - name: Create or Update Coverage Comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ![Coverage Badge](https://img.shields.io/endpoint?url=https://gist.githubusercontent.com/${{ env.GIST_OWNER }}/${{ secrets.GIST_ID }}/raw/coverage.${{ env.REPO_NAME }}.main.json)
          edit-mode: replace
          reactions: eyes
